import type { Appointment, Profile } from "./types"

export const mockDoctors: Profile[] = [
  {
    id: "d1",
    user_type: "doctor",
    first_name: "Sarah",
    last_name: "Chen",
    email: "sarah.chen@medscribe.com",
    phone: "(555) 101-2020",
    specialization: "Cardiology",
    bio: "Board-certified cardiologist with 12 years of experience.",
  },
  {
    id: "d2",
    user_type: "doctor",
    first_name: "James",
    last_name: "Rivera",
    email: "james.rivera@medscribe.com",
    phone: "(555) 202-3030",
    specialization: "Neurology",
    bio: "Specializes in neurological disorders and stroke treatment.",
  },
  {
    id: "d3",
    user_type: "doctor",
    first_name: "Amara",
    last_name: "Osei",
    email: "amara.osei@medscribe.com",
    phone: "(555) 303-4040",
    specialization: "General Practice",
    bio: "Family medicine specialist focused on preventive care.",
  },
]

export const mockPatients: Profile[] = [
  {
    id: "p1",
    user_type: "patient",
    first_name: "Michael",
    last_name: "Thompson",
    email: "m.thompson@email.com",
    phone: "(555) 501-6060",
  },
  {
    id: "p2",
    user_type: "patient",
    first_name: "Emily",
    last_name: "Davis",
    email: "e.davis@email.com",
    phone: "(555) 602-7070",
  },
  {
    id: "p3",
    user_type: "patient",
    first_name: "Robert",
    last_name: "Kim",
    email: "r.kim@email.com",
    phone: "(555) 703-8080",
  },
  {
    id: "p4",
    user_type: "patient",
    first_name: "Lisa",
    last_name: "Nguyen",
    email: "l.nguyen@email.com",
    phone: "(555) 804-9090",
  },
  {
    id: "p5",
    user_type: "patient",
    first_name: "David",
    last_name: "Martinez",
    email: "d.martinez@email.com",
    phone: "(555) 905-1010",
  },
]

export const mockAppointments: Appointment[] = [
  {
    id: "a1",
    patient_id: "p1",
    doctor_id: "d1",
    title: "Annual Heart Checkup",
    description: "Routine cardiac examination including ECG and blood pressure monitoring.",
    scheduled_at: "2026-02-12T09:00:00Z",
    duration_minutes: 45,
    status: "scheduled",
    notes: "",
    created_at: "2026-02-01T10:00:00Z",
    updated_at: "2026-02-01T10:00:00Z",
    patient: mockPatients[0],
    doctor: mockDoctors[0],
  },
  {
    id: "a2",
    patient_id: "p2",
    doctor_id: "d2",
    title: "Migraine Follow-up",
    description: "Follow-up consultation for chronic migraine treatment plan adjustments.",
    scheduled_at: "2026-02-12T10:30:00Z",
    duration_minutes: 30,
    status: "scheduled",
    notes: "",
    created_at: "2026-02-03T14:00:00Z",
    updated_at: "2026-02-03T14:00:00Z",
    patient: mockPatients[1],
    doctor: mockDoctors[1],
  },
  {
    id: "a3",
    patient_id: "p3",
    doctor_id: "d3",
    title: "General Wellness Visit",
    description: "Comprehensive physical examination and wellness screening.",
    scheduled_at: "2026-02-11T14:00:00Z",
    duration_minutes: 30,
    status: "completed",
    notes: "Patient reported feeling well overall. Blood work ordered.",
    created_at: "2026-01-28T09:00:00Z",
    updated_at: "2026-02-11T15:00:00Z",
    patient: mockPatients[2],
    doctor: mockDoctors[2],
  },
  {
    id: "a4",
    patient_id: "p4",
    doctor_id: "d1",
    title: "Echocardiogram Review",
    description: "Review results from recent echocardiogram and discuss treatment options.",
    scheduled_at: "2026-02-10T11:00:00Z",
    duration_minutes: 30,
    status: "completed",
    notes: "Echocardiogram results normal. Continue current medication.",
    created_at: "2026-01-25T08:00:00Z",
    updated_at: "2026-02-10T12:00:00Z",
    patient: mockPatients[3],
    doctor: mockDoctors[0],
  },
  {
    id: "a5",
    patient_id: "p5",
    doctor_id: "d2",
    title: "Nerve Conduction Study",
    description: "Diagnostic nerve conduction study for numbness in extremities.",
    scheduled_at: "2026-02-09T15:30:00Z",
    duration_minutes: 60,
    status: "cancelled",
    notes: "Patient rescheduled due to scheduling conflict.",
    created_at: "2026-01-20T11:00:00Z",
    updated_at: "2026-02-08T09:00:00Z",
    patient: mockPatients[4],
    doctor: mockDoctors[1],
  },
  {
    id: "a6",
    patient_id: "p1",
    doctor_id: "d3",
    title: "Lab Results Review",
    description: "Review recent blood work results and adjust medications if needed.",
    scheduled_at: "2026-02-13T08:30:00Z",
    duration_minutes: 20,
    status: "scheduled",
    notes: "",
    created_at: "2026-02-05T16:00:00Z",
    updated_at: "2026-02-05T16:00:00Z",
    patient: mockPatients[0],
    doctor: mockDoctors[2],
  },
  {
    id: "a7",
    patient_id: "p2",
    doctor_id: "d1",
    title: "Stress Test Consultation",
    description: "Pre-test consultation and preparation for cardiac stress test.",
    scheduled_at: "2026-02-14T13:00:00Z",
    duration_minutes: 30,
    status: "scheduled",
    notes: "",
    created_at: "2026-02-06T10:00:00Z",
    updated_at: "2026-02-06T10:00:00Z",
    patient: mockPatients[1],
    doctor: mockDoctors[0],
  },
  {
    id: "a8",
    patient_id: "p3",
    doctor_id: "d2",
    title: "EEG Monitoring",
    description: "Scheduled EEG monitoring session for seizure activity assessment.",
    scheduled_at: "2026-02-08T09:00:00Z",
    duration_minutes: 90,
    status: "completed",
    notes: "EEG results showed no abnormal activity. Patient stable.",
    created_at: "2026-01-15T12:00:00Z",
    updated_at: "2026-02-08T11:00:00Z",
    patient: mockPatients[2],
    doctor: mockDoctors[1],
  },
]
